name: gops

make_step: #定制make操作步骤,选项有以下几种，默认bump+clog,多选项按顺序执行
  - bump
  - clog
latest_version_name: Unreleased # 最新未发布的版本名称
commit_filters: # commit过滤器
  - all
version_name_with_date: true # version名称是否包含日期
version_name_with_author: true # version名称是否包含创建者
issue_uri_format: https://github.com/sandwich-go/%s/issues # issue地址
commit_uri_format: https://github.com/sandwich-go/%s/commits/%s # commit地址,name,commit_id
merge_duplicate_commit: true # 是否合并commit相同的提交
commit_with_author_at_date: true # commit信息中是否包含作者、日期
short_hash_len: 7 # commit id长度
issue_prefix: # issue前缀 #71
  - #
sem_initial_version: v1.3.0 #初始版本号
sem_master_branch_name: main # 主分支名称
sem_initial_branch: 1.3 #初始的分支版本，只需major和minor


